// ==UserScript==
// @name ITA-Matrix-Powertools
// @namespace https://github.com/SteppoFF/ita-matrix-powertools
// @description Adds new features and builds fare purchase links for ITA Matrix
// @version __VERSION__
// @require https://greasemonkey.github.io/gm4-polyfill/gm4-polyfill.js
// @grant GM.getValue
// @grant GM_setValue
// @grant GM.setValue
// @grant GM_setValue
// @include http*://matrix.itasoftware.com/*
// ==/UserScript==

/*
 Written by paul21, Steppo & Adam Hwang (IAkH) of FlyerTalk.com
 http://www.flyertalk.com/forum/members/paul21.html
 Includes contriutions by https://github.com/SteppoFF/ita-matrix-powertools/blob/master/AUTHORS
 Copyright Reserved -- At least share with credit if you do
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool:
//     `npm run build`
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
